spring.config.import=optional:file:.env[.properties]

server.port=${PORT}
spring.application.name=historial-service

# MySQL
spring.datasource.url=${DB_HISTORIAL_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# JWT — mismo secret que los demas servicios
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Claude API
claude.api.key=${CLAUDE_API_KEY}
claude.model=${CLAUDE_MODEL}

# URL del MS Chatbot (para obtener interacciones en CU012)
chatbot.service.url=${CHATBOT_SERVICE_URL}
