# Puerto del microservicio
server.port=8084

# Nombre del microservicio
spring.application.name=historial-service

# Desactivar datasource mientras no hay BD conectada
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Clave secreta JWT compartida con todos los microservicios
jwt.secret=kidcare-secret-key-2024-segura-32chars
jwt.expiration=86400000